export default {
  clientList: null,
  kkmList: null,
  kkmModelList: null,
  isClientListLoading: false,
  isKkmListLoading: false,
  isKkmModelListLoading: false,
  clientListError: null,
  kkmListError: null,
  kkmModelListError: null,
  ofdList: [
    "Такском",
    "Первый ОФД",
    "Калуга астра",
    "Контур",
    "Автономно",
    "Петер сервис",
  ],
  noSystemList: ["ЕНВД", "УСН", "УСН доход-расход", "ОСН", "Патент", "ЕСХН"],
  noTypeList: ["Услуги", "Торговля", "Услуги + торговля"],
};
